[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"
author = "Christopher Cialone <ccialone0929@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
